import { NextRequest, NextResponse } from "next/server";
import { promises as fs } from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { db } from "@/lib/db";
import { getStorage, mediaPath } from "@/lib/storage";
import { probe, transcode, validateAssets, cleanTemp } from "@/lib/media-worker";
import { computeSwarmId } from "@/lib/swarm";

/**
 * POST /api/media/videos/[id]/upload
 * Receives the source video file (multipart/form-data), stores it, probes
 * it, then runs the async transcode → HLS/CMAF packaging pipeline.
 *
 * This is NOT synchronous — the response returns immediately with status
 * QUEUED, and the pipeline runs in the background, updating the job status
 * as it progresses. The client polls /status.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const video = await db.video.findUnique({ where: { id } });
  if (!video) {
    return NextResponse.json({ error: "video not found" }, { status: 404 });
  }

  const formData = await req.formData();
  const file = formData.get("file") as File | null;
  if (!file) {
    return NextResponse.json({ error: "file required" }, { status: 400 });
  }

  // Basic upload validation — reject non-video MIME types.
  if (!file.type.startsWith("video/")) {
    return NextResponse.json({ error: "file must be a video" }, { status: 400 });
  }

  // Read the file into a buffer (for the demo; a production system would
  // stream to disk for large files).
  const buf = Buffer.from(await file.arrayBuffer());
  const sourceHash = createHash("sha256").update(buf).digest("hex");

  // Store the source.
  const storage = getStorage();
  const sourceRel = mediaPath(id, "source", file.name || "source.mp4");
  await storage.write(sourceRel, buf);

  // Probe the source.
  const tmpPath = path.join(process.cwd(), "storage", "tmp", `${id}-source`);
  await fs.mkdir(path.dirname(tmpPath), { recursive: true });
  await fs.writeFile(tmpPath, buf);
  const probeResult = await probe(tmpPath);

  // Save the source metadata.
  await db.videoSource.create({
    data: {
      videoId: id,
      sourceHash,
      originalName: file.name,
      storagePath: sourceRel,
      fileSize: probeResult.fileSize,
      duration: probeResult.duration,
      width: probeResult.width,
      height: probeResult.height,
      codec: probeResult.codec,
      audioCodec: probeResult.audioCodec,
      frameRate: probeResult.frameRate,
      bitrate: probeResult.bitrate,
    },
  });

  // Update the video with duration + a placeholder thumbnail.
  await db.video.update({
    where: { id },
    data: { durationSec: Math.round(probeResult.duration) },
  });

  // Mark the job as QUEUED, then kick off the async pipeline.
  await db.mediaProcessingJob.updateMany({
    where: { videoId: id, status: "UPLOADING" },
    data: { status: "QUEUED" },
  });

  // Run the pipeline in the background (non-blocking).
  runPipeline(id, tmpPath).catch(async (err) => {
    console.error(`[media pipeline] video ${id} failed:`, err);
    await db.mediaProcessingJob.updateMany({
      where: { videoId: id },
      data: { status: "FAILED", error: String(err).slice(0, 500) },
    });
    await cleanTemp(path.dirname(tmpPath));
  });

  return NextResponse.json({
    videoId: id,
    status: "QUEUED",
    source: {
      duration: probeResult.duration,
      width: probeResult.width,
      height: probeResult.height,
      codec: probeResult.codec,
    },
  });
}

/**
 * The async transcode → package → validate → publish pipeline.
 * Updates the MediaProcessingJob status at each step.
 */
async function runPipeline(videoId: string, sourcePath: string) {
  const storage = getStorage();
  const outDir = path.join(process.cwd(), "storage", "videos", videoId, "v1");

  // PROCESSING
  await db.mediaProcessingJob.updateMany({
    where: { videoId },
    data: { status: "PROCESSING", startedAt: new Date() },
  });

  const { renditions, masterManifest } = await transcode(
    sourcePath,
    outDir,
    "cpu-safe",
    async (pct) => {
      await db.mediaProcessingJob.updateMany({
        where: { videoId },
        data: { progress: pct },
      });
    }
  );

  // PACKAGING (manifest is already generated by transcode)
  await db.mediaProcessingJob.updateMany({
    where: { videoId },
    data: { status: "PACKAGING", progress: 100 },
  });

  // VALIDATING
  await db.mediaProcessingJob.updateMany({
    where: { videoId },
    data: { status: "VALIDATING" },
  });
  const valid = await validateAssets(outDir, renditions);
  if (!valid) throw new Error("asset validation failed");

  // Save renditions + manifest + swarms to the DB.
  const manifestVersion = "v1";
  for (const r of renditions) {
    const rendition = await db.videoRendition.create({
      data: {
        videoId,
        resolution: r.id,
        height: r.height,
        width: r.width,
        bitrate: r.bitrate,
        codec: "h264",
        manifestPath: path.join("videos", videoId, manifestVersion, r.id, "index.m3u8"),
      },
    });
    // Create the swarm for this rendition.
    const swarmId = computeSwarmId(videoId, rendition.id, manifestVersion);
    await db.swarm.create({
      data: {
        swarmId,
        videoId,
        renditionId: rendition.id,
        manifestVersion,
      },
    });
  }

  const masterHash = createHash("sha256")
    .update(await fs.readFile(masterManifest))
    .digest("hex");
  await db.videoManifest.create({
    data: {
      videoId,
      version: manifestVersion,
      hash: masterHash,
      manifestPath: path.join("videos", videoId, manifestVersion, "master.m3u8"),
    },
  });

  // READY
  await db.mediaProcessingJob.updateMany({
    where: { videoId },
    data: { status: "READY", completedAt: new Date() },
  });

  // Update the video with the master manifest URL + a poster (first frame).
  await db.video.update({
    where: { id: videoId },
    data: {
      videoUrl: `/api/media/videos/${videoId}/manifest`,
      thumbnailUrl: `/api/media/videos/${videoId}/manifest/master.m3u8`,
    },
  });

  // Clean up the temp source.
  await cleanTemp(path.dirname(sourcePath));
}
